package com.taskcenter.model;

public enum TaskActivityType {
    TASK_CREATED,
    TITLE_UPDATED,
    DESCRIPTION_UPDATED,
    STATUS_UPDATED,
    PRIORITY_UPDATED,
    ISSUE_TYPE_UPDATED,
    DUE_DATE_UPDATED,
    DUE_DATE_SNOOZED,
    STORY_POINTS_UPDATED,
    SPRINT_ASSIGNED,
    SPRINT_REMOVED
}
